FROM siewyanhoh/shohmesos:v3.1
MAINTAINER SiewYan <siew.yan.hoh@cern.ch>

RUN yum install -y python-matplotlib make which gcc-c++

RUN pip install histogrammar

RUN wget http://shoh.web.cern.ch/shoh/public/CentOS-CERN.repo -O /etc/yum.repos.d/CentOS-CERN.repo && yum clean all && rm -rf /var/cache/yum/*

#Build connector while docker run
ENV SPARKHOME /opt/spark
ENV PATH $PATH:/opt/hadoop/bin:/opt/jdk/bin
ENV JAVA_HOME /opt/jdk
RUN wget http://shoh.web.cern.ch/shoh/public/CentOS-CERN.repo -O /etc/yum.repos.d/CentOS-CERN.repo && \
    wget http://shoh.web.cern.ch/shoh/public/RPM-GPG-KEY-cern -O /etc/pki/rpm-gpg/RPM-GPG-KEY-cern && \
    yum install -y xrootd-client xrootd-client-libs xrootd-client-devel && \
    yum clean all && rm -rf /var/cache/yum/*

RUN wget http://shoh.web.cern.ch/shoh/public/hadoop-xrootd-connector.tar.gz -O /hadoop-xrootd-connector.tar.gz
RUN tar -zxf /hadoop-xrootd-connector.tar.gz -C /
WORKDIR /hadoop-xrootd-connector
RUN make clean 2>/dev/null && make all
RUN mv /hadoop-xrootd-connector/EOSfs.jar /opt/hadoop/share/hadoop/common/lib/EOSfs.jar
RUN mv /hadoop-xrootd-connector/libjXrdCl.so /opt/hadoop/lib/native/libjXrdCl.so
RUN make clean 2>/dev/null
WORKDIR /
RUN rm -rf hadoop-xrootd-connector
RUN rm hadoop-xrootd-connector.tar.gz